CURRENCIES = (
    ("Afghan Afghani", "Afghan Afghani - AFN (؋)"),
    ("Algerian Dinar", "Algerian Dinar - DZD (دج)"),
    ("Argentine Peso", "Argentine Peso - ARS ($)"),
    ("Armenian Dram", "Armenian Dram - AMD (AMD)"),
    ("Aruban Guilder", "Aruban Guilder - AWG (ƒ)"),
    ("Australian Dollar", "Australian Dollar - AUD (AU$)"),
    ("Azerbaijan Manat", "Azerbaijan Manat - AZN (ман)"),
    ("Bahamian Dollar", "Bahamian Dollar - BSD ($)"),
    ("Bahraini Dinar", "Bahraini Dinar - BHD (.د.ب)"),
    ("Baht", "Baht - THB (฿)"),
    ("Balboa", "Balboa - PAB (B/.)"),
    ("Barbados Dollar", "Barbados Dollar - BBD ($)"),
    ("Belarusian Ruble", "Belarusian Ruble - BYN (BYR)"),
    ("Belize Dollar", "Belize Dollar - BZD (BZ$)"),
    ("Bermudian Dollar", "Bermudian Dollar - BMD (BD$)"),
    ("Boliviano", "Boliviano - BOB ($b)"),
    ("Bolívar fuerte venezolano", "Bolívar fuerte venezolano - VEF (Bs)"),
    ("Brazilian Real", "Brazilian Real - BRL (R$)"),
    ("Brunei Dollar", "Brunei Dollar - BND ($)"),
    ("Bulgarian Lev", "Bulgarian Lev - BGN (лв)"),
    ("Burundi Franc", "Burundi Franc - BIF (FBu)"),
    ("CFA Franc BCEAO", "CFA Franc BCEAO - XOF (CFA)"),
    ("CFA Franc BEAC", "CFA Franc BEAC - XAF (FCFA)"),
    ("CFP Franc", "CFP Franc - XPF (F)"),
    ("Canadian Dollar", "Canadian Dollar - CAD (C$)"),
    ("Cape Verde Escudo", "Cape Verde Escudo - CVE ($)"),
    ("Cayman Islands Dollar", "Cayman Islands Dollar - KYD ($)"),
    ("Chilean Peso", "Chilean Peso - CLP ($)"),
    ("Colombian Peso", "Colombian Peso - COP ($)"),
    ("Comoro Franc", "Comoro Franc - KMF (CF)"),
    ("Convertible Mark", "Convertible Mark - BAM (KM)"),
    ("Cordoba Oro", "Cordoba Oro - NIO (C$)"),
    ("Costa Rican Colon", "Costa Rican Colon - CRC (₡)"),
    ("Croatian Kuna", "Croatian Kuna - HRK (kn)"),
    ("Czech Koruna", "Czech Koruna - CZK (Kč)"),
    ("Dalasi", "Dalasi - GMD (D)"),
    ("Danish Krone", "Danish Krone - DKK (kr)"),
    ("Djibouti Franc", "Djibouti Franc - DJF (Fdj)"),
    ("Dobra", "Dobra - STD (Db)"),
    ("Dominican Peso", "Dominican Peso - DOP (RD$)"),
    ("Dong", "Dong - VND (₫)"),
    ("East Carribbean Dollar", "East Carribbean Dollar - XCD ($)"),
    ("Egyptian Pound", "Egyptian Pound - EGP (£)"),
    ("Ethiopian Birr", "Ethiopian Birr - ETB (Br)"),
    ("Euro", "Euro - EUR (€)"),
    ("Falkland Islands Pound", "Falkland Islands Pound - FKP (£)"),
    ("Fiji Dollar", "Fiji Dollar - FJD ($)"),
    ("Forint", "Forint - HUF (Ft)"),
    ("Franc Congolais", "Franc Congolais - CDF (FC)"),
    ("Ghanaian Cedi", "Ghanaian Cedi - GHS (GH₵)"),
    ("Gibraltar Pound", "Gibraltar Pound - GIP (£)"),
    ("Gourde", "Gourde - HTG (G)"),
    ("Guarani", "Guarani - PYG (Gs)"),
    ("Guinea Franc", "Guinea Franc - GNF (FG)"),
    ("Guyana Dollar", "Guyana Dollar - GYD ($)"),
    ("Hong Kong Dollar", "Hong Kong Dollar - HKD (HK$)"),
    ("Hryvnia", "Hryvnia - UAH (₴)"),
    ("Iceland Krona", "Iceland Krona - ISK (kr)"),
    ("Indian Rupee", "Indian Rupee - INR (₹)"),
    ("Iraqi Dinar", "Iraqi Dinar - IQD (ع.د)"),
    ("Israeli New Sheqel", "Israeli New Sheqel - ILS (₪)"),
    ("Jamaican Dollar", "Jamaican Dollar - JMD (J$)"),
    ("Jordanian Dinar", "Jordanian Dinar - JOD (JD)"),
    ("Kenyan Shilling", "Kenyan Shilling - KES (Ksh)"),
    ("Kina", "Kina - PGK (K)"),
    ("Kip", "Kip - LAK (₭)"),
    ("Korean Won", "Korean Won - KRW (₩)"),
    ("Kuwaiti Dinar", "Kuwaiti Dinar - KWD (د.ك)"),
    ("Kwacha", "Kwacha - MWK (MK)"),
    ("Kwanza", "Kwanza - AOA (Kz)"),
    ("Kyat", "Kyat - MMK (K)"),
    ("Lari", "Lari - GEL (GEL)"),
    ("Lebanese Pound", "Lebanese Pound - LBP (.ل.ل)"),
    ("Lek", "Lek - ALL (Lek)"),
    ("Lempira", "Lempira - HNL (L)"),
    ("Leone", "Leone - SLL (LE)"),
    ("Liberian Dollar", "Liberian Dollar - LRD ($)"),
    ("Libyan dinar", "Libyan dinar - LYD (ل.د)"),
    ("Lilangeni", "Lilangeni - SZL (L)"),
    ("Loti", "Loti - LSL (L)"),
    ("Macedonian Denar", "Macedonian Denar - MKD (ден)"),
    ("Malagasy Ariary", "Malagasy Ariary - MGA (Ar)"),
    ("Malaysian Ringgit", "Malaysian Ringgit - MYR (RM)"),
    ("Mauritius Rupee", "Mauritius Rupee - MUR (₨)"),
    ("Mexican Peso", "Mexican Peso - MXN ($)"),
    ("Moldovan Leu", "Moldovan Leu - MDL (L)"),
    ("Moroccan Dirham", "Moroccan Dirham - MAD (د.م.)"),
    ("Mozambican Metical", "Mozambican Metical - MZN (MT)"),
    ("Naira", "Naira - NGN (₦)"),
    ("Nakfa", "Nakfa - ERN (ናቕፋ)"),
    ("Namibian Dollar", "Namibian Dollar - NAD ($)"),
    ("Nepalese Rupee", "Nepalese Rupee - NPR (₨)"),
    ("Netherlands Antillan Guilder", "Netherlands Antillan Guilder - ANG (ƒ)"),
    ("New Taiwan Dollar", "New Taiwan Dollar - TWD (NT$)"),
    ("New Zealand Dollar", "New Zealand Dollar - NZD ($)"),
    ("Ngultrum", "Ngultrum - BTN (Nu.)"),
    ("Norwegian Krone", "Norwegian Krone - NOK (kr)"),
    ("Nuevo Sol", "Nuevo Sol - PEN (S/.)"),
    ("Ouguiya", "Ouguiya - MRO (UM)"),
    ("Pa'anga", "Pa'anga - TOP (T$)"),
    ("Pakistan Rupee", "Pakistan Rupee - PKR (₨)"),
    ("Pataca", "Pataca - MOP (MOP$)"),
    ("Peso Uruguayo", "Peso Uruguayo - UYU ($U)"),
    ("Philippine Peso", "Philippine Peso - PHP (₱)"),
    ("Pound Sterling", "Pound Sterling - GBP (£)"),
    ("Pula", "Pula - BWP (P)"),
    ("Qatari Rial", "Qatari Rial - QAR (﷼)"),
    ("Quetzal", "Quetzal - GTQ (Q)"),
    ("Rand", "Rand - ZAR (R)"),
    ("Rial Omani", "Rial Omani - OMR (﷼)"),
    ("Riel", "Riel - KHR (៛)"),
    ("Romanian Lei", "Romanian Lei - RON (lei)"),
    ("Rufiyaa", "Rufiyaa - MVR (Rf)"),
    ("Rupiah", "Rupiah - IDR (Rp)"),
    ("Russian Ruble", "Russian Ruble - RUB (руб.)"),
    ("Rwanda Franc", "Rwanda Franc - RWF (R₣)"),
    ("Saint Helena Pound", "Saint Helena Pound - SHP (£)"),
    ("Saudi Riyal", "Saudi Riyal - SAR (﷼)"),
    ("Serbian Dinar", "Serbian Dinar - RSD (РСД)"),
    ("Seychelles Rupee", "Seychelles Rupee - SCR (₨)"),
    ("Singapore Dollar", "Singapore Dollar - SGD (S$)"),
    ("Solomon Islands Dollar", "Solomon Islands Dollar - SBD ($)"),
    ("Som", "Som - KGS (сом)"),
    ("Somali Shilling", "Somali Shilling - SOS (S)"),
    ("Somoni", "Somoni - TJS (TJS)"),
    ("Sri Lanka Rupee", "Sri Lanka Rupee - LKR (₨)"),
    ("Surinamese Dollar", "Surinamese Dollar - SRD ($)"),
    ("Swedish Krona", "Swedish Krona - SEK (kr)"),
    ("Swiss Franc", "Swiss Franc - CHF (CHF)"),
    ("Taka", "Taka - BDT (৳)"),
    ("Tala", "Tala - WST (WS$)"),
    ("Tanzanian Shilling", "Tanzanian Shilling - TZS (TSh)"),
    ("Tenge", "Tenge - KZT (₸)"),
    ("Trinidad and Tobago Dollar", "Trinidad and Tobago Dollar - TTD (TT$)"),
    ("Tugrik (Tugrug)", "Tugrik (Tugrug) - MNT (₮)"),
    ("Tunisian Dinar", "Tunisian Dinar - TND (د.ت)"),
    ("Turkmenistani Manat", "Turkmenistani Manat - TMT (T)"),
    ("Türk lirası (TL)", "Türk lirası (TL) - TRY (₺)"),
    ("UAE Dirham", "UAE Dirham - AED (AED)"),
    ("US Dollar", "US Dollar - USD ($)"),
    ("Uganda Shilling", "Uganda Shilling - UGX (USh)"),
    ("Uzbekistan Sum", "Uzbekistan Sum - UZS (сум)"),
    ("Vatu", "Vatu - VUV (VT)"),
    ("Yemeni Rial", "Yemeni Rial - YER (﷼)"),
    ("Yen", "Yen - JPY (¥)"),
    ("Yuan Renminbi", "Yuan Renminbi - CNY (¥)"),
    ("Zambian Kwacha", "Zambian Kwacha - ZMW (ZK)"),
    ("Zloty", "Zloty - PLN (zł)"),
)
