# Generated by Django 3.2.2 on 2021-05-10 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="isHelpFulCount",
            field=models.PositiveIntegerField(
                default=0,
                editable=False,
                help_text="how many viewers found this article helpful.",
                verbose_name="is helpful count",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="isNotHelpFulCount",
            field=models.PositiveIntegerField(
                default=0,
                editable=False,
                help_text="how many viewers did not find this article helpful.",
                verbose_name="is not helpful count",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                help_text="the content slug. Accepts unicode characters.",
                max_length=150,
                unique=True,
                verbose_name="slug",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                help_text="comment author. Should be a Member model.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comments",
                related_query_name="comment",
                to="articles.member",
                verbose_name="author",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="likes",
            field=models.PositiveIntegerField(
                default=0,
                editable=False,
                help_text="comment likes.",
                verbose_name="likes",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="replies",
            field=models.ManyToManyField(
                blank=True,
                help_text="comment replies.",
                related_name="commentReplies",
                related_query_name="commentReply",
                to="articles.Comment",
                verbose_name="replies",
            ),
        ),
    ]
