# Generated by Django 3.2.2 on 2021-05-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_alter_member_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="articleview",
            name="ipAddress",
            field=models.GenericIPAddressField(
                editable=False,
                help_text="client IP address",
                null=True,
                verbose_name="ip address",
            ),
        ),
    ]
