# Generated by Django 3.2.2 on 2021-05-18 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_articleview_ipaddress"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="replies",
        ),
        migrations.AddField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                help_text="null indicates this is a root comment, else, the field should point to the comment being replied to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                related_query_name="reply",
                to="articles.comment",
                verbose_name="replies",
            ),
        ),
    ]
