# Generated by Django 3.2.2 on 2021-05-10 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="isHelpFulCount",
            field=models.PositiveIntegerField(
                default=0,
                help_text="how many members found this lesson useful.",
                verbose_name="is helpful count",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="isNotHelpFulCount",
            field=models.PositiveIntegerField(
                default=0,
                help_text="how many members did not find this lesson useful.",
                verbose_name="is not helpful count",
            ),
        ),
    ]
