# Generated by Django 3.2.2 on 2021-05-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="postview",
            name="ipAddress",
            field=models.GenericIPAddressField(
                editable=False,
                help_text="client IP address",
                null=True,
                verbose_name="ip address",
            ),
        ),
    ]
